// backend/utils/quotePdf.js
const PDFDocument = require("pdfkit");

/**
 * Return a Buffer containing a PDF for a quote.
 * Keep it dependency-light for now (PDFKit only).
 */
async function renderQuotePdf({ quote, org }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: "A4", margin: 48 });

      const chunks = [];
      doc.on("data", (c) => chunks.push(c));
      doc.on("end", () => resolve(Buffer.concat(chunks)));

      const orgName =
        (org && (org.name || org.orgName)) ||
        "Quotify";

      // Header
      doc
        .fontSize(18)
        .text(orgName, { align: "left" })
        .moveDown(0.25);

      doc
        .fontSize(12)
        .fillColor("#333333")
        .text(`Quote: ${quote.quoteNumber}`)
        .text(`Status: ${quote.status}`)
        .text(`Issued: ${new Date(quote.issueDate).toLocaleString()}`)
        .moveDown(1);

      // Customer
      doc
        .fontSize(12)
        .fillColor("#111111")
        .text("Customer", { underline: true })
        .moveDown(0.25);

      const cs = quote.customerSnapshot || {};
      doc
        .fontSize(11)
        .fillColor("#333333")
        .text(cs.name || "—")
        .text(cs.email || "")
        .text(cs.phone || "")
        .text(cs.address || "")
        .moveDown(1);

      // Title / Notes
      if (quote.title) {
        doc.fontSize(12).fillColor("#111111").text("Title", { underline: true });
        doc.fontSize(11).fillColor("#333333").text(String(quote.title)).moveDown(0.75);
      }

      if (quote.notes) {
        doc.fontSize(12).fillColor("#111111").text("Notes", { underline: true });
        doc.fontSize(11).fillColor("#333333").text(String(quote.notes)).moveDown(0.75);
      }

      // Line items
      doc.fontSize(12).fillColor("#111111").text("Line items", { underline: true }).moveDown(0.5);

      const lines = Array.isArray(quote.lines) ? quote.lines : [];
      if (lines.length === 0) {
        doc.fontSize(11).fillColor("#333333").text("No line items.");
      } else {
        lines.forEach((l, idx) => {
          const qty = Number(l.quantity || 0);
          const name = String(l.name || "Item");

          // Prefer stored snapshot fields if present, otherwise compute from unitPriceExTax
          const exStored = l.lineSubtotalExTax;
          const taxStored = l.lineTax;
          const incStored = l.lineTotalIncTax;

          const ex = Number(exStored != null ? exStored : qty * Number(l.unitPriceExTax || 0));
          const tax = Number(taxStored != null ? taxStored : 0);
          const inc = Number(incStored != null ? incStored : ex + tax);

          doc
            .fontSize(11)
            .fillColor("#111111")
            .text(`${idx + 1}. ${name}`);

          const desc = String(l.description || "");
          if (desc) {
            doc.fontSize(10).fillColor("#555555").text(desc);
          }

          doc
            .fontSize(10)
            .fillColor("#333333")
            .text(`Qty: ${qty}   Unit: ${l.unit || ""}`)
            .text(`Ex GST: ${ex.toFixed(2)}   GST: ${tax.toFixed(2)}   Inc GST: ${inc.toFixed(2)}`)
            .moveDown(0.75);
        });
      }

      // Totals
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor("#111111").text("Totals", { underline: true }).moveDown(0.25);

      doc
        .fontSize(11)
        .fillColor("#333333")
        .text(`Subtotal (ex GST): ${Number(quote.subtotalExTax || 0).toFixed(2)}`)
        .text(`GST: ${Number(quote.taxTotal || 0).toFixed(2)}`)
        .fontSize(12)
        .fillColor("#111111")
        .text(`Total (inc GST): ${Number(quote.totalIncTax || 0).toFixed(2)}`);

      // Footer
      doc.moveDown(2);
      doc.fontSize(9).fillColor("#777777").text("Generated by Quotify", { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { renderQuotePdf };